name: Build, deploy & check Mage-OS Nightly

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '20 11 * * *'
  workflow_dispatch:
    inputs:
      composer_cache_dir:
        description: A key to version the composer cache. Can be incremented if you need to bust the cache.
        required: false
        default: ''

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    name: "generate & deploy"
    with:
      repo: https://nightly.mage-os.org
      remote_dir: /var/www/nightly.mage-os.org/html/
      entrypoint: src/make/mageos-nightly.js
      delete: false
    secrets:
      SERVER_SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
      REMOTE_USER: ${{ secrets.REMOTE_USER }}
