name: Build, deploy & check Mirror

on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'The composer repository url'
        required: true
        default: 'https://preview-mirror.mage-os.org/'
        type: choice
        options:
          - https://preview-mirror.mage-os.org/
          - https://mirror.mage-os.org/
      remote_dir:
        description: 'The deploy target directory on the repo host'
        required: true
        default: '/var/www/preview-mirror.mage-os.org/html/'
        type: choice
        options:
          - /var/www/preview-mirror.mage-os.org/html/
          - /var/www/mirror.mage-os.org/html/
      versions:
        description: 'Comma-separated list of versions to build (e.g. 2.4.5-p13,2.4.6-p11). Leave empty to build all versions'
        required: false
        default: ''
        type: string
  push:
    branches:
      - main

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    name: "generate & deploy"
    if: contains('["vinai", "rhoerr", "fballiano", "mage-os-ci"]', github.actor)
    with:
      repo: ${{ (github.event_name == 'workflow_dispatch' && inputs.repo) || 'https://preview-mirror.mage-os.org/' }}
      remote_dir: ${{ (github.event_name == 'workflow_dispatch' && inputs.remote_dir) || '/var/www/preview-mirror.mage-os.org/html/' }}
      entrypoint: src/make/mirror.js
      delete: ${{ inputs.versions == '' }}
      versions: ${{ inputs.versions || '' }}
    secrets:
      SERVER_SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
      REMOTE_USER: ${{ secrets.REMOTE_USER }}

  integrity-check:
    needs: [deploy]
    uses: ./.github/workflows/integrity-check.yml
    with:
      repo: ${{ (github.event_name == 'workflow_dispatch' && inputs.repo) || 'https://preview-mirror.mage-os.org/' }}
    secrets:
      COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}
